version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rakutabi
hooks:
  BeforeInstall:
    - location: aws_scripts/setup_server.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: aws_scripts/deploy_build_server.sh
      timeout: 600
      runas: ec2-user
