version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rakutabi
permissions:
  - object: /rakutabi
    pattern: "*.sh"
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: aws_scripts/setup_server.sh
      timeout: 600
      runas: ec2-user
