version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rakutabi
hooks:
  BeforeInstall:
    - location: aws_scripts/codedeploy_scripts/01_remove_previous_codes.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: aws_scripts/codedeploy_scripts/02_deploy_build_server.sh
      timeout: 600
      runas: ec2-user
