version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rakutabi
hooks:
  AfterInstall:
    - location: /home/ec2-user/rakubabi/awsscripts/serup_server.sh
      timeout: 120
      runas: ec2-user
